name: flame_fire_atlas
description: Easy to use texture atlases for the flame engine created with the
  fire atlas editor
version: 2.0.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_fire_atlas
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - tools

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  archive: ^3.3.9
  flame: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
