name: flame_isolate
description: Flame wrapper for integral_isolates making multi-threading easy in Flame
version: 0.7.0
repository: https://github.com/flame-engine/flame/blob/main/packages/flame_isolate
topics:
  - flame
  - isolate

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flame: ^2.0.0
  flutter:
    sdk: flutter
  integral_isolates: ^0.5.1

dev_dependencies:
  flame_lint: ^2.0.0
  flame_test: ^2.0.0
  flutter_test:
    sdk: flutter
  test: any

