name: flame_markdown_example
description: Simple project to showcase the usage of flame_markdown
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flame: ^2.0.0
  flame_markdown: ^0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^2.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/