name: examples
description: A set of small examples showcasing each feature provided by the Flame Engine.
homepage: https://github.com/flame-engine/flame/tree/main/examples
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  dashbook: ^0.1.15
  flame: ^2.0.0
  flame_audio: ^3.0.0
  flame_forge2d: ^0.19.0
  flame_isolate: ^0.7.0
  flame_lottie: ^0.5.0
  flame_noise: ^0.4.0
  flame_spine: ^0.3.0
  flame_svg: ^2.0.0
  flame_tiled: ^2.0.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  jenny: ^1.4.0
  meta: ^1.12.0
  padracing: ^1.0.0
  provider: ^6.0.5
  rogue_shooter: ^0.1.0
  trex_game: ^0.1.0

dev_dependencies:
  flame_lint: ^2.0.0
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/animations/
    - assets/images/
    - assets/images/tile_maps/
    - assets/images/layers/
    - assets/images/parallax/
    - assets/images/parallax/
    - assets/images/rogue_shooter/
    - assets/spine/
    - assets/svgs/
    - assets/tiles/
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/yarn/
