name: doc_flame_examples
description: Documentation examples
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flame: ^2.0.0
  flame_rive: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/images/